name: CustomMessage
main: Assassiner354\CustomMessage\Main
version: 2.0.1-BETA
api: [3.0.0]
author: Assaasiner354/A354-PH + some changes by iZeaoGamer
website: https://github.com/iZeaoGamer/CustomMessage
