#Config File for CustomMessage
#Made by Assassiner354


## CUSTOM OPTIONS:

custom-whitelist: true
## Choose whether you want custom whitelist message to show below. (If you set this to true, whitelist.reason and whitelist.message option will show in the whitelist message. If you set "custom-whitelist" to false, the default whitelist message will show.

custom-ban: true
## Choose whether you want custom ban message to show below (If you set this to true, banned.message and  no.banned.reason.message option will show in the ban message. If you set "custom-ban" to false, the default ban message will show.

## NEW: Whitelist message - Put your whitelist message below! Here are the variables you can use for the whitelist message:
## {line} - New line.
## & - For color code.
whitelist.message: "&cServer currently whitelisted!"


### NEW: BANNED MESSAGE AND BANNED REASONS SECTION BELOW:

## NEW: Banned message - Put your banned message below (When a banned player tries to join the server) Here are the variables for the banned message.
## {line} - New lne.
## {reason} - When a user get's banned for a specific reason, it'll display by using {reason} variable.
## & - For color code.

banned.message: "&cYou have been banned.{line}&bReason: &3{reason}" ##Ban message for the reason only.
no.banned.reason.message: "&cYou have been banned!" ##Without the ban reason.
